# Generated by Django 5.2.4 on 2025-08-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_followers_profile_timestamp_profile_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.FileField(blank=True, upload_to="images/"),
        ),
    ]
