version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: apupos
      POSTGRES_USER: apupos_user
      POSTGRES_PASSWORD: apupos_pass

volumes:
  postgres_data:
