# Generated by Django 5.1.6 on 2025-06-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apupos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apupo",
            options={"ordering": ["-id"]},
        ),
    ]
