# Generated by Django 5.2.2 on 2025-06-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apupos", "0004_apupo_created_at_apupolike_apupo_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="apupo",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apupos.apupo",
            ),
        ),
    ]
