# Generated by Django 5.2.4 on 2025-07-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apupos", "0005_apupo_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apupo",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apupos.apupo",
            ),
        ),
    ]
